spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${db.host}/${db.database}
    username: ${db.user}
    password: ${db.pass}
  cache:
    type: redis
  redis:
    host: ${redis.server}
    port: ${redis.port}

logging:
  level: 
    org:
      hibernate: 
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

dynamodb:
  region: us-east-1

exceptions:
  classes:
    notfound: com.br.alldreams.jupiter.base.exception.service.ItemNaoEncontradoServiceException	
    dadosinvalidos: com.br.alldreams.jupiter.base.exception.service.DadosInvalidosServiceException




#Mensagens internas
mensagens:
  mensagens:
    nao-encontrado:
      descricao: "%s não encontrado."
      codigo: "0001"
      classe: ${exceptions.classes.notfound}
    campos-invalidos:
      descricao: "Campos invalidos (%s)."
      codigo: "0002"
      classe: ${exceptions.classes.dadosinvalidos}