spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://${db.host}/${db.database}?useTimezone=true&serverTimezone=UTC
    username: ${db.user}
    password: ${db.pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#  cache:
#    type: redis
#  redis:
#    host: ${redis.server}
#    port: ${redis.port}

dynamodb:
  region: us-east-1

exceptions:
  classes:
    notfound: com.br.alldreams.jupiter.base.exception.service.ItemNaoEncontradoServiceException	
    dadosinvalidos: com.br.alldreams.jupiter.base.exception.service.DadosInvalidosServiceException
    sempermissao: com.br.alldreams.jupiter.base.exception.service.SemPermissaoServiceException
    sitenaoexiste: com.br.alldreams.jupiter.base.exception.service.SiteNaoExisteServiceException

management:
  endpoint:
    health:
      show-details: never
      show-components: never



#Mensagens internas
mensagens:
  mensagens:
    nao-encontrado:
      descricao: "%s não encontrado."
      codigo: "0001"
      classe: ${exceptions.classes.notfound}
    campos-invalidos:
      descricao: "Campos invalidos (%s)."
      codigo: "0002"
      classe: ${exceptions.classes.dadosinvalidos}
    sem-permissao:
      descricao: "Não possui permissão para acessar essa informação ou o usuário não está logado."
      codigo: "0003"
      classe: ${exceptions.classes.sempermissao}
    site-nao-existe:
      descricao: "O site que tentou acessar não exite ou não está mais disponivel."
      codigo: "0004"
      classe: ${exceptions.classes.sitenaoexiste}